const ServiceData = [
  {
    name: "Business Assessment",
    desc: "Meet the Panorama Assessment App – pinpoint key areas for improvement through detailed analysis, guiding you with informed, actionable steps. Gain employee insights with a comprehensive sentiment analysis for a panoramic view of your business landscape.",
    img: "/assesmentDisplay.png",
    type: "Assessment",
    url: "/assessment",
  },
  
  {
    name: "Fractional CFO",
    desc: "Access a flexible financial solution for businesses in need of immediate structure without the commitment of a full-time CFO.",
    img: "/solution/CFOfractional.png",
    type: "Solutions",
    url: "/fractionalcfo",
  },
  {
    name: "Panorama Finance App",
    desc: "Streamline your business finances: track costs, send invoices with a click, and manage expenditures, all in one platform.",
    img: "/solution/finance.png",
    type: "Solutions",
    url: "/fractionalcfo",
  },
  {
    name: "Services",
    desc: "Count on our Business Support for guidance and assistance, ensuring your success every step of the way, anytime, anywhere.",
    img: "/solution/services.png",
    type: "Solutions",
    url: "/services",
  },
  {
    name: "Business Consulting",
    desc: "Our expert consultants closely collaborate with your business, understanding its unique needs. From financial optimization to operational efficiency, we provide comprehensive services to empower you in navigating the complexities of the business landscape.",
    img: "/solution/businessConsulting.png",
    type: "Consulting",
    url: "/consulting",
  },
  {
    name: "Research",
    desc: "Panorama provides innovative research services, offering valuable insights and informed decision-making for organizations. Our team delivers actionable data, industry trends, and in-depth competitive analysis to drive your organization's growth and strategic initiatives. By leveraging our research expertise, stay ahead of the competition, make data-driven decisions, and seize opportunities to propel your business forward.",
    img: "/solution/research.png",
    type: "Consulting",
    url: "/rdd",
  },
  {
    name: "Training",
    desc: "Panorama's training programs go beyond imparting knowledge; they cultivate skills that yield results. Recognizing the crucial role of a skilled workforce, we take pride in seamlessly and efficiently training our clients' teams. Our customized sessions cover various areas, equipping your personnel with the tools and expertise needed for success.",
    img: "/solution/training.png",
    type: "Consulting",
    url: "/",
  },
  {
    name: "Documentation & Development",
    desc: "Panorama excels in meticulous documentation services, helping organizations streamline processes and gain clarity. Our expertise lies in crafting comprehensive and user-friendly documents to enhance efficiency. Whether developing policies, procedures, or workflow diagrams, our services ensure optimized operations and seamless workflows. With meticulous attention to detail, we establish clear guidelines that enhance productivity across your business.",
    img: "/solution/docs.png",
    type: "Consulting",
    url: "/rdd",
  },
  {
    name: "Courses",
    desc: "Panorama's training programs equip you with essential competencies crucial for business success. Focused on skills like effective pitch deck construction, financial management, and key business operations, active participation ensures you gain the knowledge and tools to drive substantial business growth.",
    img: "/solution/courses.png",
    type: "Knowledge",
    url: "/",
  },
  {
    name: "Events and Sessions",
    desc: "Panorama Access is a user-friendly platform offering easy exploration of past and upcoming sessions. It serves as a valuable repository, allowing convenient access to details from previous events. Stay up-to-date with the latest developments and seize future opportunities in your field with the Panorama platform.",
    img: "/solution/events.png",
    type: "Knowledge",
    url: "/",
  },
  {
    name: "Resources",
    desc: "Panorama Access is a centralized platform with a user-friendly interface, making it easy to explore past sessions and events. It serves as a valuable repository, keeping you well-informed about upcoming events. The platform allows easy access to details from previous sessions, ensuring you stay up-to-date with the latest developments and seize future opportunities in your field.",
    img: "/solution/resources.png",
    type: "Knowledge",
    url: "/",
  },
  {
    name: "Skills ",
    desc: "Panorama aims to develop personal skills like positivity, responsibility, and quick learning, along with fostering teamwork and fundamental abilities such as communication and problem-solving.",
    img: "/solution/skills.png",
    type: "Knowledge",
    url: "/",
  },
  {
    name: "Theory of change",
    desc: "Panorama provides Theory of Change services—a structured approach for planning social change within organizations. It outlines causal pathways connecting activities to desired outcomes, helping define key elements for achieving impact.",
    img: "/solution/theory.png",
    type: "Impact",
    url: "/",
  },
  {
    name: "Prioritise what you measure",
    desc: "In our service, we stress the importance of prioritizing specific metrics for a meaningful impact. Focusing on these metrics provides a comprehensive understanding of success factors, allowing effective resource allocation toward areas driving desired outcomes.",
    img: "/solution/priotorize.png",
    type: "Impact",
    url: "/",
  },

  {
    name: "Choose the  level of evidence",
    desc: "At Panorama, we assess evidence levels to gauge the impact of phenomena or interventions. This crucial evaluation ensures the reliability and validity of presented evidence, fostering more informed discussions and accurate decision-making based on reliable data.",
    img: "/solution/evidence.png",
    type: "Impact",
    url: "/",
  },
  {
    name: "Select your sources and tools",
    desc: "At Panorama, we utilize a range of tools like surveys, data analysis, case studies, and more to measure impact. These sources provide insights into the effectiveness of your efforts, guiding you choose the most relevant ones based on your goals and resources.",
    img: "/solution/source.png",
    type: "Impact",
    url: "/",
  },
  {
    name: "Investment Teaser",
    desc: "We provide an Investment Teaser, a concise document highlighting key aspects of your business to attract potential investors. With details on your unique value proposition, market potential, financial projections, and growth opportunities, our Investment Teaser helps you effectively communicate your business's investment potential. Panorama is committed to supporting your fundraising efforts by providing this valuable resource.",
    img: "/solution/teaser.png",
    type: "Investment",
    url: "/",
  },
  {
    name: "Valuation",
    desc: "Panorama  consultants use a thorough method to evaluate and establish the fair market value of your company. Whether for a merger, acquisition, or strategic decision-making, our valuation service goes beyond numbers, providing insightful analyses of your financial landscape. This empowers you to make informed decisions and strategically position your business for success.",
    img: "/solution/valuation.png",
    type: "Investment",
    url: "/",
  },
  {
    name: "Investment summary",
    desc: "Within Panorama Service, the investment summary is tailored to the investor's goals and objectives, factoring in their risk tolerance and time horizon. A financial advisor utilizes this information to design an optimal investment strategy, crucial in shaping the composition of the investor's financial portfolio.",
    img: "/solution/summary.png",
    type: "Investment",
    url: "/",
  },
  {
    name: "Investor Deck",
    desc: "In the Panorama framework, a pitch deck, also known as a start-up or investor pitch deck, functions as a presentation that offers potential investors comprehensive information about your business. Contrary to popular belief, the primary goal of a pitch deck is not solely to secure funding, but rather to effectively progress to the next phase of discussions or meetings.",
    img: "/solution/resourcesi.png",
    type: "Investment",
    url: "/",
  },
  {
    name: "Data Room",
    desc: "Our service includes a data room—a consolidated collection of documents providing investors with a comprehensive understanding of your business. The goal is to equip investors with necessary information for thorough due diligence, facilitating the creation of an investment memo to be shared and discussed with their team.",
    img: "/solution/data.png",
    type: "Investment",
    url: "/",
  },
  {
    name: "UI/UX Development",
    desc: "Our dedicated team crafts captivating UIs that align with your brand, paired with seamless UX for enjoyable and intuitive customer interactions.",
    img: "/solution/code.webp",
    type: "IT",
    url: "/digital_service",
  },
  {
    name: "Website Development",
    desc: "Crafting customized digital platforms that precisely reflect your brand vision. Our customized solutions guarantee your online presence aligns seamlessly with your business goals, creating a distinct and compelling representation in the digital landscape.",
    img: "/solution/ui.webp",
    type: "IT",
    url: "/digital_service",
  },
  {
    name: "Data Room",
    desc: "As part of our service, we offer a data room that serves as a consolidated collection of documents designed to provide investors with a comprehensive understanding of your business. The primary goal of the data room is to equip investors with the necessary information to conduct thorough due diligence on your company. This allows them to gather all the essential details required to create an investment memo, which can be shared and discussed with their team.",
    img: "/solution/data.png",
    type: "IT",
    url: "/digital_service",
  },
];

export default ServiceData;
