const ServiceData = [
  {
    name: "Business Assessment",
    desc: "Unlock your business potential with our comprehensive assessment. Identify your short-comings, analyse their nature and formulate the best solutions to overcome your challenges with us.",
    img: "/solution/assesmentDisplay.png",
    type: "Assessment",
    url: "/assessment",
  },
  {
    name: "Fractional CFO",
    desc: "Access high-level financial advice without the commitment of a full-time CFO through our Fractional CFO services. We provide expert guidance tailored to the specific needs of your business. With our flexible solution, you can benefit from the strategic insights and financial expertise of a seasoned CFO, optimizing your financial decision-making and driving sustainable growth. Our Fractional CFO services offer the perfect balance of expertise and cost-efficiency to support your business's financial success.",
    img: "/solution/CFOfractional.png",
    type: "Solutions",
    url: "/fractionalcfo",
  },
  {
    name: "Services",
    desc: "Transform your business dreams into reality with our comprehensive range of services. We provide a one-stop solution for all your business needs by connecting you with the right service providers. From consulting and advisory services to marketing, technology, and beyond, we offer a diverse range of solutions under one umbrella. Streamline your operations and save valuable time and effort by accessing all the services required to fuel your business growth through a single point of contact. Let us be your trusted partner in connecting you with the resources you need to thrive.",
    img: "/solution/services.png",
    type: "Solutions",
    url: "/services",
  },
  {
    name: "Business Consulting",
    desc: "Panorama, a management consulting firm, offers a comprehensive range of services designed to enhance organizational performance and support the achievement of clients' goals. The firm collaborates closely with clients to identify areas requiring improvement, formulate effective strategies, implement solutions, and foster positive transformations. By leveraging their expertise, industry knowledge, and analytical abilities, Panorama empowers organizations to optimize their processes, overcome obstacles, and attain long-lasting growth.",
    img: "/solution/businessConsulting.png",
    type: "Consulting",
    url: "/consulting",
  },
  {
    name: "Research",
    desc: "Harness the power of cutting-edge research services. Panorama offers innovative research services that enable organizations to tap into the power of valuable insights and make informed decisions. Our dedicated team provides actionable data, industry trends, and in-depth competitive analysis to fuel your organization's growth and drive strategic initiatives. By leveraging our research services, you can stay ahead of the competition, make data-driven decisions, and seize opportunities that propel your organization forward. Unlock the full potential of your business and gain a competitive edge with our exceptional research expertise.",
    img: "/solution/research.png",
    type: "Consulting",
    url: "/rdd",
  },
  {
    name: "Training",
    desc: "Panorama's services empower organizations by driving their growth through trans-formative training programs. Our dynamic workshops and engaging training sessions cover a wide range of areas, from leadership development to specialized skill-building. Designed to enhance employee capabilities and foster personal and professional growth, our programs equip your team with the skills necessary to excel in their roles. By leveraging our training solutions, you can unleash the full potential of your workforce and propel your organization forward.",
    img: "/solution/training.png",
    type: "Consulting",
    url: "/",
  },
  {
    name: "Documentation & Development",
    desc: "Streamline your processes and ensure clarity. Panorama's meticulous documentation services enable organizations to streamline their processes and achieve clarity. Our expertise lies in creating comprehensive and user-friendly documents that enhance efficiency. Whether it's developing policies and procedures or crafting workflow diagrams, our services ensure optimized operations and seamless workflow within your organization. With our meticulous attention to detail, we help establish clear guidelines that enhance productivity across your business.",
    img: "/solution/docs.png",
    type: "Consulting",
    url: "/rdd",
  },
  {
    name: "Courses",
    desc: "Panorama's training programs are designed to equip you with essential competencies that are crucial for business success. These programs focus on developing skills such as constructing effective pitch decks, proficient financial management, and mastering critical aspects of business operations. By actively participating in these programs, you will acquire the necessary knowledge and tools to drive your business forward and achieve substantial growth..",
    img: "/solution/courses.png",
    type: "Knowledge",
    url: "/",
  },
  {
    name: "Events and Sessions",
    desc: "Panorama Access is a centralized platform that provides a user-friendly interface for convenient exploration of past sessions and events. It keeps you well-informed about upcoming sessions and events, serving as a valuable repository of information. With the Panorama platform, you can easily access and retrieve details about previous sessions and events, allowing you to revisit valuable content. Moreover, it ensures you stay up-to-date with the latest developments and seize future opportunities in your field.",
    img: "/solution/events.png",
    type: "Knowledge",
    url: "/",
  },
  {
    name: "Resources",
    desc: "Panorama services offer you access to a wide array of industry-specific documents and templates, providing you with comprehensive resources to support your success. These meticulously crafted resources are specifically designed to streamline your workflow, allowing you to save valuable time and effort. By utilizing our tools, you will not only enhance your efficiency but also gain the confidence and capability needed to achieve your goals and thrive in your endeavors. Panorama services are dedicated to empowering you with the necessary tools and support to excel in your professional endeavors.",
    img: "/solution/resources.png",
    type: "Knowledge",
    url: "/",
  },
  {
    name: "Skills ",
    desc: "Panorama aims to cultivate personal skills centered around positivity, responsibility, quick learning, and workplace safety. It also highlights teamwork skills involving effective collaboration, support for team members, and active contribution to shared projects. In addition, Panorama places emphasis on fundamental skills like excellent communication, adept information management, numerical proficiency, and proficient problem-solving",
    img: "/solution/skills.png",
    type: "Knowledge",
    url: "/",
  },
  {
    name: "Theory of change",
    desc: "Panorama provide services related to the Theory of Change. This framework serves as a structured approach to understanding and planning for social change within an organization. It outlines the causal pathways that connect the organization's activities and interventions to the desired outcomes. By identifying key assumptions, strategies, and resources, the Theory of Change helps in defining the necessary elements to achieve the desired impact.",
    img: "/solution/theory.png",
    type: "Impact",
    url: "/",
  },
  {
    name: "Prioritise what you measure",
    desc: "As part of our service, we emphasize the importance of prioritizing in-depth metrics to achieve a meaningful impact. By concentrating on specific metrics, you can gain a comprehensive understanding of the factors that contribute to success. This enables you to channel your efforts and allocate resources effectively towards the areas that drive the desired outcomes.",
    img: "/solution/priotorize.png",
    type: "Impact",
    url: "/",
  },

  {
    name: "Choose the  level of evidence",
    desc: "As part of our work at Panorama, we also engage in assessing the level of evidence when considering the impact of a particular phenomenon or intervention. This assessment is crucial in determining the reliability and validity of the evidence presented, enabling a more informed evaluation of the magnitude of the impact. By carefully selecting the appropriate level of evidence, we ensure that conclusions drawn about the impact are based on robust and trustworthy data. This contributes to more accurate decision-making and fosters informed discussions on the subject matter.",
    img: "/solution/evidence.png",
    type: "Impact",
    url: "/",
  },
  {
    name: "Select your sources and tools",
    desc: "In the context of Panorama, various sources and tools can be utilized to measure impact. These include surveys/questionnaires, data analysis, case studies, interviews/focus groups, impact assessment frameworks, external research/reports, feedback/testimonials, and comparative analysis. These sources and tools enable the gathering of both quantitative and qualitative data, assessing changes, and providing insights into the effectiveness of your efforts. It is important to select the most relevant ones based on your specific goals and the resources available to you..",
    img: "/solution/source.png",
    type: "Impact",
    url: "/",
  },
  {
    name: "Investment Teaser",
    desc: "In addition to the comprehensive training programs and services provided by Panorama, we also offer an Investment Teaser. This specialized resource is designed to assist you in attracting potential investors for your business. The Investment Teaser is a concise and compelling document that highlights the key aspects of your business, including its unique value proposition, market potential, financial projections, and growth opportunities. By utilizing our Investment Teaser, you can effectively communicate the investment potential of your business and capture the interest of potential investors. Panorama understands the importance of securing investment and aims to support you in your fundraising efforts through this valuable resource.",
    img: "/solution/teaser.png",
    type: "Investment",
    url: "/",
  },
  {
    name: "Investment summary",
    desc: "In the context of Panorama Service, the investment summary is formulated by considering the specific goals and objectives of the investor. By taking into account the investor's risk tolerance and time horizon, a financial advisor can design an optimal investment strategy. These factors are pivotal in shaping the composition of the investor's financial portfolio.",
    img: "/solution/summary.png",
    type: "Investment",
    url: "/",
  },
  {
    name: "Investor Deck",
    desc: "In the Panorama framework, a pitch deck, also known as a start-up or investor pitch deck, functions as a presentation that offers potential investors comprehensive information about your business. Contrary to popular belief, the primary goal of a pitch deck is not solely to secure funding, but rather to effectively progress to the next phase of discussions or meetings.",
    img: "/solution/resourcesi.png",
    type: "Investment",
    url: "/",
  },
  {
    name: "Data Room",
    desc: "As part of our service, we offer a data room that serves as a consolidated collection of documents designed to provide investors with a comprehensive understanding of your business. The primary goal of the data room is to equip investors with the necessary information to conduct thorough due diligence on your company. This allows them to gather all the essential details required to create an investment memo, which can be shared and discussed with their team.",
    img: "/solution/data.png",
    type: "Investment",
    url: "/",
  },
  {
    name: "UI/UX Development",
    desc: "Our team excels at UI/UX Development through a blend of creativity, expertise, and meticulous processes. We start by thoroughly understanding your goals and your target audience. We conduct in-depth research to grasp user behaviors and preferences. Then, we craft visually captivating User Interfaces (UI) that resonate with your brand identity. Our User Experience (UX) designs focus on seamless navigation, ensuring every interaction is intuitive and efficient.",
    img: "/solution/code.webp",
    type: "IT",
    url: "/digital_service",
  },
  {
    name: "Website Development",
    desc: "Our team designs and builds websites that not only look great but also function seamlessly, providing a strong online presence and enhancing user engagement.In website development we use MERN(MongoDB, Express,React,Node.js) Stack and AWS .",
    img: "/solution/ui.webp",
    type: "IT",
    url: "/digital_service",
  },
  {
    name: "Data Room",
    desc: "As part of our service, we offer a data room that serves as a consolidated collection of documents designed to provide investors with a comprehensive understanding of your business. The primary goal of the data room is to equip investors with the necessary information to conduct thorough due diligence on your company. This allows them to gather all the essential details required to create an investment memo, which can be shared and discussed with their team.",
    img: "/solution/data.png",
    type: "IT",
    url: "/digital_service",
  },
];

export default ServiceData;
