const ServiceData = [
  {
    name: "Business Assessment",
    desc: "Unlock your business potential with our comprehensive assessment. Identify your short-comings, analyse their nature and formulate the best solutions to overcome your challenges with us.",
    img: "/solution/assesmentBusiness.png",
    type: "Assessment",
    url: "/",
  },
  {
    name: "Fractional CFO",
    desc: "Access high-level financial advice without the commitment of a full-time CFO overTextthrough our Fractional CFO services. We provide expert guidance tailored to the specific needs of your business. With our flexible solution, you can benefit from the strategic insights and financial expertise of a seasoned CFO, optimizing your financial decision-making and driving sustainable growth. Our Fractional CFO services offer the perfect balance of expertise and cost-efficiency to support your business's financial success.",
    img: "/solution/CFOfractional.png",
    type: "Solutions",
    url: "/",
  },
  {
    name: "Services",
    desc: "Transform your business dreams into reality with our comprehensive range of services. We provide a one-stop solution for all your business needs by connecting you with the right service providers. From consulting and advisory services to marketing, technology, and beyond, we offer a diverse range of solutions under one umbrella. Streamline your operations and save valuable time and effort by accessing all the services required to fuel your business growth through a single point of contact. Let us be your trusted partner in connecting you with the resources you need to thrive.",
    img: "/solution/services.png",
    type: "Solutions",
    url: "/",
  },
  {
    name: "Business Consulting",
    desc: "Management consulting encompasses the provision of consulting services to organizations with the aim of enhancing their performance and assisting them in achieving their organizational objectives. It involves working closely with clients to identify areas for improvement, develop strategies, implement solutions, and drive positive change, bring their expertise, industry knowledge, and analytical skills to help organizations optimize their processes, overcome challenges, and achieve sustainable growth.",
    img: "/solution/businessConsulting.png",
    type: "Consulting",
    url: "/",
  },
  {
    name: "Research",
    desc: "Harness the power of cutting-edge research services to uncover invaluable insights and drive informed decision-making. Our team delivers actionable data, industry trends, and comprehensive competitive analysis to fuel your organization's growth and support strategic initiatives. With our research services, you can stay ahead of the curve, make data-driven decisions, and seize opportunities that propel your organization forward. Gain a competitive edge and unleash the full potential of your business with our research expertise.",
    img: "/solution/research.png",
    type: "Consulting",
    url: "/",
  },
  {
    name: "Training",
    desc: "Empower your workforce and drive organizational growth with our trans-formative training programs. From leadership development to specialized skill-building, we deliver dynamic workshops and engaging training sessions. Our programs are designed to enhance employee capabilities, foster personal and professional growth, and equip your team with the skills needed to excel in their roles. With our training solutions, you can unleash the full potential of your workforce and propel your organization forward.",
    img: "/solution/training.png",
    type: "Consulting",
    url: "/",
  },
  {
    name: "Documentation & Development",
    desc: "Streamline your processes and ensure clarity with our meticulous documentation services. We specialize in creating comprehensive and user-friendly documents that streamline your processes. Whether it's developing policies and procedures or crafting workflow diagrams, our services ensure optimized efficiency and facilitate seamless operations within your organization. With our attention to detail, we help you establish clear guidelines and enhance productivity across your business.",
    img: "/solution/docs.png",
    type: "Consulting",
    url: "/",
  },
  {
    name: "Courses",
    desc: "Our training programs aim to equip you with vital competencies, such as constructing effective pitch decks, managing finances proficiently, and mastering various critical aspects of business. By participating in these programs, you will gain the necessary knowledge and tools to propel your business forward and achieve significant growth.",
    img: "/solution/courses.png",
    type: "Knowledge",
    url: "/",
  },
  {
    name: "Events and Sessions",
    desc: "Gain access to a centralized platform where you can conveniently explore past sessions and events while staying up-to-date with upcoming ones. This resourceful hub allows you to retrieve information about previous sessions and events, enabling you to revisit valuable content and stay informed about future opportunities.",
    img: "/solution/events.png",
    type: "Knowledge",
    url: "/",
  },
  {
    name: "Resources",
    desc: "Get the resources you need to succeed, from industry-specific documents to templates. Our resources are designed to save you time, effort and empower you to succeed",
    img: "/solution/resources.png",
    type: "Knowledge",
    url: "/",
  },
  {
    name: "Skills ",
    desc: "Panorama aims to cultivate personal skills centered around positivity, responsibility, quick learning, and workplace safety. It also highlights teamwork skills involving effective collaboration, support for team members, and active contribution to shared projects. In addition, Panorama places emphasis on fundamental skills like excellent communication, adept information management, numerical proficiency, and proficient problem-solving",
    img: "/solution/skills.png",
    type: "Knowledge",
    url: "/",
  },
  {
    name: "Theory of change",
    desc: "The Theory of Change is a framework that outlines the causal pathways through which an organization's activities and interventions lead to desired outcomes. It provides a structured approach to understanding and planning for social change by identifying the key assumptions, strategies, and resources necessary to achieve the desired impact.",
    img: "/solution/theory.png",
    type: "Impact",
    url: "/",
  },
  {
    name: "Prioritise what you measure",
    desc: "To create a significant impact, it is crucial to prioritize the metrics you measure in depth. By focusing on specific metrics, you can gain a deeper understanding of the factors that drive success and effectively channel your efforts and resources.",
    img: "/solution/priotorize.png",
    type: "Impact",
    url: "/",
  },

  {
    name: "Choose the  level of evidence",
    desc: "When considering the impact of a certain phenomenon or intervention, it is important to assess the level of evidence supporting that impact. This assessment helps determine the reliability and validity of the evidence, allowing for a more informed evaluation of the extent of the impact. By selecting the appropriate level of evidence, one can ensure that the conclusions drawn about the impact are based on robust and trustworthy data, contributing to more accurate decision-making and informed discussions.",
    img: "/solution/evidence.png",
    type: "Impact",
    url: "/",
  },
  {
    name: "Select your sources and tools",
    desc: "To measure the impact, consider using surveys/questionnaires, data analysis, case studies, interviews/focus groups, impact assessment frameworks, external research/reports, feedback/testimonials, and comparative analysis. These sources and tools help gather quantitative and qualitative data, assess changes, and provide insights into the effectiveness of your efforts. Select the most relevant ones based on your goals and available resources.",
    img: "/solution/source.png",
    type: "Impact",
    url: "/",
  },
  {
    name: "Investment Teaser",
    desc: "Master essential skills, including pitch deck building, financial management, and other key areas of business. Our training programs are designed to give you the knowledge and tools you need to take your business to the next level. market leadership, ownership of proprietary technology, significant revenue growth, strong alliances and/or partnerships, an extensive sales network, superior production capabilities, an experienced management team.",
    img: "/solution/teaser.png",
    type: "Investment",
    url: "/",
  },
  {
    name: "Investment summary",
    desc: "An investor's financial portfolio is shaped by a set of objectives that define their goals. A financial advisor employs an investment objective to devise the most advantageous approach for attaining these goals. The investor's risk tolerance and time horizon play a crucial role in establishing the investment objective.",
    img: "/solution/summary.png",
    type: "Investment",
    url: "/",
  },
  {
    name: "Investor Deck",
    desc: "A pitch deck, commonly referred to as a start-up or investor pitch deck, serves as a presentation that provides potential investors with detailed insights into your business. Surprisingly, the main objective of a pitch deck is not solely to secure funding but rather to successfully advance to the next stage of discussions or meetings.",
    img: "/solution/deck.png",
    type: "Investment",
    url: "/",
  },
  {
    name: "Data Room",
    desc: "At its core, a data room is a compilation of documents that aims to provide investors with comprehensive insights into your business. The primary objective of a data room is to equip investors with the necessary information to conduct thorough due diligence on your company. This process enables them to gather all the essential details needed to create an investment memo, which can then be shared and discussed with their team.",
    img: "/solution/data.png",
    type: "Investment",
    url: "/",
  },
];

export default ServiceData;
