const WorkData = [
  { id: "02",url:'/solution/Corporate.png', name: "Corporate", desc: "At Panorama, we specialize in working with corporations to help them achieve their goals. Our expert services are designed to enhance efficiency and profitability by offering consulting, technology solutions, and support. We can assist your corporation in optimizing processes, implementing innovative solutions, and providing ongoing guidance to drive success and maximize your organization's potential." },
  { id: "01",url:'/solution/startup.png', name: "Startups", desc: "Panorama services are specifically designed to assist startups in achieving growth. We offer comprehensive support and guidance to help startups navigate the challenges they face in their journey towards expansion. Our services encompass strategic planning, market research, business development, funding assistance, and operational optimization. By leveraging our expertise and resources, startups can enhance their chances of success and accelerate their growth trajectory." },
  { id: "06",url:'/solution/smes.png', name: "SMEs", desc: "Panorama aims to emphasize the importance of small and medium-sized enterprises (SMEs) and acknowledges their substantial presence, accounting for 99% of all businesses. Defining SMEs accurately is crucial as it establishes their eligibility for accessing financial support and allows them to take advantage of specialized programs designed specifically for these enterprises in the context of Bangladesh." },
  { id: "05",url:'/solution/vc.png', name: "Venture Capital", desc: "Panorama collaborates in the field of venture capital (VC), which involves providing funding to startups and small businesses with high growth potential. This type of private equity investment is typically sourced from affluent investors, investment banks, and various financial institutions. Venture capital investments are intended to support companies that are anticipated to experience substantial long-term growth." },
  { id: "04",url:'/solution/ngos.png', name: "NGOs", desc: "Panorama provides support and assistance to non-governmental organizations (NGOs), which are voluntary associations of individuals or organizations that operate independently of government affiliation. NGOs are established with the purpose of offering services or advocating for public policies. While there are a few NGOs that operate as for-profit corporations, the majority of them are nonprofit organizations." },
 
  { id: "03",url:'/solution/gov.png', name: "Government ", desc: "Panorama will offer services that encompass organizations closely affiliated with state or local government.  In addition, we will be working with ICT departments, offering support and solutions tailored to their specific needs and objectives. We can collaborate with these departments in various ways. Our aim is to assist ICT departments in achieving their goals and driving efficiency and innovation within their organizations." },
  
];
export default WorkData